name: sv_pipe_qdnaseq
channels:
    - conda-forge
    - bioconda
dependencies:
    - bcftools
    - samtools
    - pysam
    - jasminesv
    - duphold
    - r-tidyverse
    - r-docopt
    - bioconductor-qdnaseq
